CREATE TABLE `driver` (
  `DriverID` INT(11) PRIMARY KEY AUTO_INCREMENT,
  `DriverName` VARCHAR(100) NOT NULL,
  `PhotoPath` VARCHAR(255) DEFAULT NULL,
  `PermanentAddress` VARCHAR(255) DEFAULT NULL,
  `TemporaryAddress` VARCHAR(255) DEFAULT NULL,
  `MobileNo` VARCHAR(15) DEFAULT NULL,
  `GuarantorName` VARCHAR(100) DEFAULT NULL,
  `GuarantorMobileNo` VARCHAR(15) DEFAULT NULL,
  `LicenseNo` VARCHAR(50) DEFAULT NULL,
  `LicenseIssueDate` DATE DEFAULT NULL,
  `LicenseExpiryDate` DATE DEFAULT NULL,
  `HAZExpiryDate` DATE DEFAULT NULL,
  `HAZLicenseNo` VARCHAR(50) DEFAULT NULL,
  `OpBalance` INT(11) DEFAULT NULL
);

CREATE TABLE `driverbankdetails` (
  `BankDetailID` INT(11)  PRIMARY KEY AUTO_INCREMENT,
  `DriverID` INT(11) DEFAULT NULL,
  `BankName` VARCHAR(100) DEFAULT NULL,
  `AccountNo` VARCHAR(50) DEFAULT NULL,
  `BranchName` VARCHAR(100) DEFAULT NULL,
  `IFSCCode` VARCHAR(20) DEFAULT NULL,
  FOREIGN KEY (`DriverID`) REFERENCES `driver` (`DriverID`) ON DELETE CASCADE
);

CREATE TABLE `driverdocuments` (
  `DocumentID` INT(11) PRIMARY KEY AUTO_INCREMENT,
  `DriverID` INT(11) DEFAULT NULL,
  `DocumentType` VARCHAR(50) DEFAULT NULL,
  `DocumentName` VARCHAR(100) DEFAULT NULL,
  `Remarks` VARCHAR(255) DEFAULT NULL,
  `DocumentPath` VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (`DriverID`) REFERENCES `driver` (`DriverID`) ON DELETE CASCADE
);

CREATE TABLE `joiningdetails` (
  `JoiningDetailsID` INT(11) PRIMARY KEY AUTO_INCREMENT,
  `DriverID` INT(11) DEFAULT NULL,
  `JoiningDate` DATE DEFAULT NULL,
  `LeaveDate` DATE DEFAULT NULL,
  `TotalDate` INT(11) DEFAULT NULL,
  `VehicleNo` VARCHAR(50) DEFAULT NULL,
  `BasicSalary` INT(11) DEFAULT NULL,
  `SalaryType` VARCHAR(50) DEFAULT NULL,
  `Allowance` INT(11) DEFAULT NULL,
  `AllowanceType` VARCHAR(50) DEFAULT NULL,
  `Remarks` VARCHAR(255) DEFAULT NULL,
  `Status` VARCHAR(50) DEFAULT NULL,
  FOREIGN KEY (`DriverID`) REFERENCES `driver` (`DriverID`) ON DELETE CASCADE
);

CREATE TABLE `vehicle` (
  `VehicleID` INT(11) PRIMARY KEY  AUTO_INCREMENT,
  `VehicleNo` VARCHAR(50) NOT NULL,
  `VehicleOwner` VARCHAR(100) DEFAULT NULL,
  `Capacity` INT(11) DEFAULT NULL,
  `PANName` VARCHAR(100) DEFAULT NULL,
  `PANCardNo` VARCHAR(20) DEFAULT NULL,
  `TareWeight` FLOAT DEFAULT NULL,
  `VehicleType` VARCHAR(100) DEFAULT NULL,
  `OwnerType` VARCHAR(500) DEFAULT NULL,
  `VehicleModelType` VARCHAR(100) DEFAULT NULL
);

CREATE TABLE `rto` (
  `RTOID` INT(11) PRIMARY KEY AUTO_INCREMENT,
  `VehicleID` INT(11) NOT NULL,
  `TaxExpiry` DATE DEFAULT NULL,
  `FitnessNo` VARCHAR(50) DEFAULT NULL,
  `FitnessExpiry` DATE DEFAULT NULL,
  `StatePermitNo` VARCHAR(50) DEFAULT NULL,
  `StatePermitExpiry` DATE DEFAULT NULL,
  `PermittedState` VARCHAR(100) DEFAULT NULL,
  `AIPPermit` VARCHAR(50) DEFAULT NULL,
  `AIPPermitExpiry` DATE DEFAULT NULL,
  `InsurancePolicyNo` VARCHAR(50) DEFAULT NULL,
  `InsuranceExpiry` DATE DEFAULT NULL,
  `ExplosiveLicNo` VARCHAR(50) DEFAULT NULL,
  `ExplosiveExpiry` DATE DEFAULT NULL,
  `PUCNo` VARCHAR(50) DEFAULT NULL,
  `PUCExpiry` DATE DEFAULT NULL,
  `CalibrationNo` VARCHAR(50) DEFAULT NULL,
  `CalibrationExpiry` DATE DEFAULT NULL,
  `NumOfComp` INT(11) DEFAULT NULL,
  FOREIGN KEY (`VehicleID`) REFERENCES `vehicle` (`VehicleID`) ON DELETE CASCADE
);


CREATE TABLE `vehicledocument` (
  `DocumentID` INT(11) PRIMARY KEY AUTO_INCREMENT,
  `VehicleID` INT(11) DEFAULT NULL,
  `DocumentType` VARCHAR(50) DEFAULT NULL,
  `DocumentName` VARCHAR(100) DEFAULT NULL,
  `Remarks` VARCHAR(255) DEFAULT NULL,
  `DocumentFile` VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (`VehicleID`) REFERENCES `vehicle` (`VehicleID`) ON DELETE CASCADE
);
